# Generated by Django 6.0.4 on 2026-04-13 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0004_stationinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('connecting', 'Connecting'), ('active', 'Active'), ('closed', 'Closed'), ('error', 'Error')], default='connecting', max_length=12, verbose_name='status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('close_reason', models.CharField(blank=True, max_length=200, verbose_name='close reason')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_sessions', to='stations.station', verbose_name='station')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'terminal session',
                'verbose_name_plural': 'terminal sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
