# Generated by Django 6.0.6 on 2026-07-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalsession',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='last seen'),
        ),
    ]
