# Generated by Django 6.0.4 on 2026-04-17 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64, verbose_name='release tag')),
                ('machine', models.CharField(choices=[('qemux86-64', 'QEMU x86-64'), ('raspberrypi4-64', 'Raspberry Pi 4 (64-bit)')], max_length=32, verbose_name='machine')),
                ('s3_key', models.CharField(max_length=512, verbose_name='S3 object key')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('cosign_bundle_s3_key', models.CharField(blank=True, max_length=512)),
                ('size_bytes', models.BigIntegerField(verbose_name='size in bytes')),
                ('is_latest', models.BooleanField(default=False, verbose_name='latest for this machine')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'image release',
                'verbose_name_plural': 'image releases',
                'ordering': ['-imported_at'],
                'constraints': [models.UniqueConstraint(fields=('tag', 'machine'), name='uniq_tag_per_machine')],
            },
        ),
    ]
