# Generated by Django 6.0.4 on 2026-04-17 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='imagerelease',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('machine',), name='uniq_latest_per_machine'),
        ),
    ]
