# Generated by Django 6.0.4 on 2026-04-17 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_imageimportjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageimportjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'image import job', 'verbose_name_plural': 'image import jobs'},
        ),
        migrations.AlterField(
            model_name='imageimportjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed at'),
        ),
        migrations.AlterField(
            model_name='imageimportjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='imageimportjob',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='error message'),
        ),
        migrations.AlterField(
            model_name='imageimportjob',
            name='image_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='images.imagerelease', verbose_name='image release'),
        ),
        migrations.AlterField(
            model_name='imageimportjob',
            name='machine',
            field=models.CharField(choices=[('qemux86-64', 'QEMU x86-64'), ('raspberrypi4-64', 'Raspberry Pi 4 (64-bit)')], max_length=32, verbose_name='machine'),
        ),
        migrations.AlterField(
            model_name='imageimportjob',
            name='mark_as_latest',
            field=models.BooleanField(default=True, verbose_name='mark as latest'),
        ),
        migrations.AlterField(
            model_name='imageimportjob',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='requested by'),
        ),
        migrations.AlterField(
            model_name='imageimportjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='imageimportjob',
            name='tag',
            field=models.CharField(max_length=64, verbose_name='release tag'),
        ),
    ]
