# Generated by Django 6.0.4 on 2026-04-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0004_alter_imageimportjob_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagerelease",
            name="rootfs_s3_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="S3 key for the extracted root_a partition, bz2-compressed. Empty means this release has not been processed for OTA yet (re-import required).",
                max_length=512,
                verbose_name="rootfs S3 object key",
            ),
        ),
        migrations.AddField(
            model_name="imagerelease",
            name="rootfs_sha256",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="rootfs SHA-256"
            ),
        ),
        migrations.AddField(
            model_name="imagerelease",
            name="rootfs_size_bytes",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="rootfs size in bytes"
            ),
        ),
    ]
