# Generated by Django 6.0.6 on 2026-06-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_imagerelease_rootfs_s3_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerelease',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete timestamp. Archived releases are hidden from the default UI list but remain available for any Deployment or ProvisioningJob that still references them.', null=True, verbose_name='archived at'),
        ),
    ]
