# Generated by Django 6.0.3 on 2026-09-02 18:51

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_imagerelease_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagerelease',
            options={'base_manager_name': 'all_objects', 'ordering': ['-imported_at'], 'verbose_name': 'image release', 'verbose_name_plural': 'image releases'},
        ),
        migrations.AlterModelManagers(
            name='imagerelease',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='imagerelease',
            name='uniq_tag_per_machine',
        ),
        migrations.RemoveConstraint(
            model_name='imagerelease',
            name='uniq_latest_per_machine',
        ),
        migrations.AddField(
            model_name='imagerelease',
            name='channel',
            field=models.CharField(default='release', help_text='Image variant/channel, baked at build time (release, dev, …). Free-form slug; no governance is enforced on it.', max_length=32, verbose_name='channel'),
        ),
        migrations.AddConstraint(
            model_name='imagerelease',
            constraint=models.UniqueConstraint(fields=('tag', 'machine', 'channel'), name='uniq_tag_per_machine_channel'),
        ),
        migrations.AddConstraint(
            model_name='imagerelease',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('machine', 'channel'), name='uniq_latest_per_machine_channel'),
        ),
    ]
