# Generated by Django 6.0.3 on 2026-09-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_imagerelease_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageimportjob',
            name='channel',
            field=models.CharField(default='release', max_length=32, verbose_name='channel'),
        ),
    ]
