# Generated by Django 6.0.3 on 2026-09-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='z. B. fm, power, device-tester', unique=True, verbose_name='key')),
                ('display_name', models.CharField(max_length=128, verbose_name='display name')),
                ('hw_repo', models.CharField(blank=True, max_length=200, verbose_name='hardware repo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'module type',
                'verbose_name_plural': 'module types',
                'ordering': ['key'],
            },
        ),
    ]
