# Generated by Django 6.0.3 on 2026-09-13 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_firmware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True, verbose_name='UID')),
                ('uid_source', models.CharField(choices=[('stm32_uid', 'STM32 UID'), ('synthetic', 'Synthetic (Sim)')], default='stm32_uid', max_length=16, verbose_name='UID source')),
                ('lifecycle_status', models.CharField(choices=[('ready', 'Ready'), ('deployed', 'Deployed'), ('defect', 'Defect'), ('in_lab', 'In Lab'), ('retired', 'Retired')], default='ready', max_length=16, verbose_name='lifecycle')),
                ('registration_status', models.CharField(choices=[('unregistered', 'Unregistered'), ('registered', 'Registered')], default='unregistered', max_length=16, verbose_name='registration')),
                ('last_reported_version', models.CharField(blank=True, max_length=64, verbose_name='last reported version')),
                ('first_seen', models.DateTimeField(blank=True, null=True, verbose_name='first seen')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='last seen')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='module_firmware.moduletype', verbose_name='module type')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['module_type', 'uid'],
                'indexes': [models.Index(fields=['uid'], name='module_firm_uid_1e5e48_idx'), models.Index(fields=['registration_status'], name='module_firm_registr_0f95c5_idx'), models.Index(fields=['lifecycle_status'], name='module_firm_lifecyc_8dba16_idx')],
            },
        ),
    ]
