# Generated by Django 6.0.3 on 2026-09-13 21:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_firmware', '0002_module'),
        ('stations', '0018_remove_station_audio_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=64, verbose_name='slot')),
                ('from_ts', models.DateTimeField(default=django.utils.timezone.now, verbose_name='from')),
                ('to_ts', models.DateTimeField(blank=True, null=True, verbose_name='to')),
                ('reason', models.CharField(blank=True, max_length=64, verbose_name='reason')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='module_firmware.module', verbose_name='module')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_assignments', to='stations.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'module assignment',
                'verbose_name_plural': 'module assignments',
                'ordering': ['-from_ts'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('to_ts__isnull', True)), fields=('module',), name='uniq_open_assignment_per_module'), models.UniqueConstraint(condition=models.Q(('to_ts__isnull', True)), fields=('station', 'slot'), name='uniq_open_assignment_per_station_slot')],
            },
        ),
    ]
