# Generated by Django 6.0.7 on 2026-09-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_firmware', '0003_moduleassignmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletype',
            name='firmware_repo',
            field=models.CharField(blank=True, help_text='GitHub owner/repo der signierten FW-Releases, z. B. OE5XRX/FW-RemoteStation', max_length=200, verbose_name='firmware repo'),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='release_asset_prefix',
            field=models.CharField(blank=True, help_text='Asset-Basisname vor -<variant>.signed.bin, z. B. fm-sa818', max_length=64, verbose_name='release asset prefix'),
        ),
    ]
