# Generated by Django 6.0.7 on 2026-09-14 11:34

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_firmware', '0004_moduletype_firmware_repo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFirmwareRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(blank=True, max_length=32, verbose_name='variant')),
                ('version', models.CharField(max_length=64, verbose_name='version')),
                ('storage_key', models.CharField(max_length=512, verbose_name='storage key')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('size_bytes', models.BigIntegerField(verbose_name='size in bytes')),
                ('cosign_bundle_key', models.CharField(blank=True, max_length=512, verbose_name='cosign bundle key')),
                ('source_repo', models.CharField(max_length=200, verbose_name='source repo')),
                ('source_tag', models.CharField(max_length=64, verbose_name='source tag')),
                ('source_github_url', models.CharField(blank=True, max_length=512, verbose_name='source URL')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='imported at')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='imported by')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmware_releases', to='module_firmware.moduletype', verbose_name='module type')),
            ],
            options={
                'verbose_name': 'module firmware release',
                'verbose_name_plural': 'module firmware releases',
                'ordering': ['module_type', 'variant', '-version'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['module_type', 'variant'], name='module_firm_module__0d87e7_idx')],
                'constraints': [models.UniqueConstraint(fields=('module_type', 'variant', 'version'), name='uniq_release_per_type_variant_version')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
