# Generated by Django 6.0.7 on 2026-09-14 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_firmware', '0005_modulefirmwarerelease'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFirmwareImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_repo', models.CharField(max_length=200, verbose_name='source repo')),
                ('tag', models.CharField(max_length=64, verbose_name='release tag')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmware_import_jobs', to='module_firmware.moduletype', verbose_name='module type')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='module_firmware.modulefirmwarerelease', verbose_name='release')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'module firmware import job',
                'verbose_name_plural': 'module firmware import jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
