# Generated by Django 6.0.3 on 2026-09-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_firmware', '0006_modulefirmwareimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='firmware_convergence',
            field=models.CharField(choices=[('ok', 'OK'), ('updating', 'Updating'), ('quarantined', 'Quarantined'), ('unknown', 'Unknown')], default='unknown', max_length=16, verbose_name='firmware convergence'),
        ),
        migrations.AddField(
            model_name='module',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='variant'),
        ),
    ]
