# Generated by Django 6.0.3 on 2026-09-25 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_firmware', '0007_module_variant_convergence'),
        ('stations', '0020_alter_stationauditlog_station'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFirmwareTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64, verbose_name='version')),
                ('scope', models.CharField(choices=[('fleet', 'Fleet default'), ('tag', 'Tag override'), ('station', 'Station override')], default='fleet', max_length=16, verbose_name='scope')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('canary_tag', models.ForeignKey(blank=True, help_text='While set, a fleet target applies only to stations in this tag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stations.stationtag', verbose_name='canary tag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firmware_targets', to='module_firmware.moduletype', verbose_name='module type')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmware_targets', to='stations.station', verbose_name='station')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmware_targets', to='stations.stationtag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'module firmware target',
                'verbose_name_plural': 'module firmware targets',
                'ordering': ['module_type', 'scope'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope', 'fleet')), fields=('module_type',), name='uniq_fleet_target_per_type'), models.UniqueConstraint(condition=models.Q(('scope', 'tag')), fields=('module_type', 'tag'), name='uniq_tag_target_per_type_tag'), models.UniqueConstraint(condition=models.Q(('scope', 'station')), fields=('module_type', 'station'), name='uniq_station_target_per_type_station')],
            },
        ),
    ]
