# Generated by Django 6.0.3 on 2026-09-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_firmware', '0008_modulefirmwaretarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFirmwareConvergenceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ok', 'OK'), ('updating', 'Updating'), ('quarantined', 'Quarantined')], default='updating', max_length=16, verbose_name='state')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='attempts')),
                ('last_error_mode', models.CharField(blank=True, choices=[('rejected', 'Rejected'), ('rolled_back', 'Rolled back'), ('transient', 'Transient')], default='', max_length=16, verbose_name='last error mode')),
                ('last_error_message', models.TextField(blank=True, verbose_name='last error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='last attempt at')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convergence_states', to='module_firmware.module', verbose_name='module')),
                ('target_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convergence_states', to='module_firmware.modulefirmwarerelease', verbose_name='target release')),
            ],
            options={
                'verbose_name': 'module firmware convergence state',
                'verbose_name_plural': 'module firmware convergence states',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('module', 'target_release'), name='uniq_convergence_per_module_release')],
            },
        ),
    ]
