# Generated by Django 6.0.3 on 2026-09-25 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_firmware', '0009_modulefirmwareconvergencestate'),
        ('stations', '0021_c_firmware_audit_event_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modulefirmwaretarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'fleet'), _negated=True), models.Q(('tag__isnull', True), ('station__isnull', True)), _connector='OR'), name='target_fleet_has_no_ref'),
        ),
        migrations.AddConstraint(
            model_name='modulefirmwaretarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'tag'), _negated=True), models.Q(('tag__isnull', False), ('station__isnull', True)), _connector='OR'), name='target_tag_has_tag_only'),
        ),
        migrations.AddConstraint(
            model_name='modulefirmwaretarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'station'), _negated=True), models.Q(('station__isnull', False), ('tag__isnull', True)), _connector='OR'), name='target_station_has_station_only'),
        ),
    ]
