# Generated by Django 6.0.3 on 2026-09-25 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_firmware', '0010_scope_check_constraints'),
        ('stations', '0021_c_firmware_audit_event_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modulefirmwaretarget',
            constraint=models.CheckConstraint(condition=models.Q(('scope', 'fleet'), ('canary_tag__isnull', True), _connector='OR'), name='canary_tag_only_on_fleet'),
        ),
    ]
