# Generated by Django 6.0.6 on 2026-06-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_drop_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_level',
            field=models.CharField(choices=[('applicant', 'Vereins-Bewerber'), ('member', 'Vereins-Mitglied'), ('staff', 'Vereins-Staff'), ('admin', 'Vereins-Admin')], default='applicant', max_length=10, verbose_name='membership level'),
        ),
    ]
