# Generated by Django 6.0.6 on 2026-06-05 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_seed_membership_levels"),
        ("stations", "0011_add_assignments"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("membership_promoted", "Membership Promoted"),
                            ("membership_demoted", "Membership Demoted"),
                            ("region_assignment_created", "Region Assignment Created"),
                            ("region_assignment_revoked", "Region Assignment Revoked"),
                            ("region_created", "Region Created"),
                            ("region_updated", "Region Updated"),
                            ("region_deleted", "Region Deleted"),
                        ],
                        max_length=32,
                        verbose_name="event type",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP address"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_audit_logs_as_actor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="stations.region",
                        verbose_name="region",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_audit_logs_as_target",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="target user",
                    ),
                ),
            ],
            options={
                "verbose_name": "account audit log",
                "verbose_name_plural": "account audit logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="accounts_ac_created_398ff2_idx"),
                    models.Index(
                        fields=["event_type", "-created_at"], name="accounts_ac_event_t_e97c58_idx"
                    ),
                    models.Index(
                        fields=["target_user", "-created_at"],
                        name="accounts_ac_target__10e769_idx",
                    ),
                ],
            },
        ),
    ]
