# Generated by Django 6.0.6 on 2026-06-12 09:17

import apps.accounts.models
import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_drop_legacy_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.avatar_upload_path, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_directory_visible',
            field=models.BooleanField(default=True, verbose_name='visible in member directory'),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='locator',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Maidenhead locator must be 2 letters + 2 digits + 2 letters (e.g. JN78AB).', regex=re.compile('^[A-R]{2}[0-9]{2}[A-X]{2}\\Z'))], verbose_name='Maidenhead locator'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='qrz_url',
            field=models.URLField(blank=True, verbose_name='QRZ URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='qth_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='QTH name'),
        ),
    ]
