# Generated by Django 6.0.6 on 2026-06-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_user_profile_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountauditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("membership_promoted", "Membership Promoted"),
                    ("membership_demoted", "Membership Demoted"),
                    ("region_assignment_created", "Region Assignment Created"),
                    ("region_assignment_revoked", "Region Assignment Revoked"),
                    ("region_created", "Region Created"),
                    ("region_updated", "Region Updated"),
                    ("region_deleted", "Region Deleted"),
                    ("user_created", "User Created"),
                    ("user_updated", "User Updated"),
                    ("user_deleted", "User Deleted"),
                    ("user_activated", "User Activated"),
                    ("user_deactivated", "User Deactivated"),
                    ("password_changed", "Password Changed"),
                    ("station_assignment_created", "Station Assignment Created"),
                    ("station_assignment_revoked", "Station Assignment Revoked"),
                ],
                max_length=32,
                verbose_name="event type",
            ),
        ),
    ]
