# Generated by Django 6.0.6 on 2026-06-13 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_lat_lon_range_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('welcome', 'Welcome (set initial password)'), ('reset', 'Password reset'), ('verify', 'Email verification')], db_index=True, max_length=16)),
                ('secret_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_created', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'token_type', 'used_at'], name='accounts_ac_user_id_715075_idx'), models.Index(fields=['secret_hash'], name='accounts_ac_secret__f48ed2_idx')],
            },
        ),
    ]
