# Generated by Django 6.0.6 on 2026-06-13 15:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_username_drop_unique'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_email_ci_unique',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('deleted_at__isnull', True), models.Q(('email', ''), _negated=True)), name='accounts_user_email_ci_unique'),
        ),
    ]
