# Generated by Django 6.0.6 on 2026-06-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_email_active_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountauditlog',
            name='event_type',
            field=models.CharField(choices=[('membership_promoted', 'Membership Promoted'), ('membership_demoted', 'Membership Demoted'), ('region_assignment_created', 'Region Assignment Created'), ('region_assignment_revoked', 'Region Assignment Revoked'), ('region_created', 'Region Created'), ('region_updated', 'Region Updated'), ('region_deleted', 'Region Deleted'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('password_changed', 'Password Changed'), ('station_assignment_created', 'Station Assignment Created'), ('station_assignment_revoked', 'Station Assignment Revoked'), ('welcome_token_sent', 'Welcome Token Sent'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_rate_limited', 'Password Reset Rate Limited'), ('password_set_from_token', 'Password Set From Token'), ('email_verify_requested', 'Email Verify Requested'), ('email_verified', 'Email Verified'), ('user_soft_deleted', 'User Soft-Deleted'), ('user_restored', 'User Restored'), ('user_hard_purged', 'User Hard-Purged')], max_length=32, verbose_name='event type'),
        ),
    ]
