# Generated by Django 6.0.7 on 2026-08-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_username_db_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_channel',
            field=models.CharField(choices=[('email', 'Nur E-Mail'), ('push', 'Nur Push'), ('both', 'E-Mail und Push')], default='email', help_text='How station alerts reach you: e-mail, push, or both.', max_length=8, verbose_name='notification channel'),
        ),
    ]
