# Generated by Django 6.0.4 on 2026-04-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='key',
            field=models.CharField(db_index=True, editable=False, help_text='SHA-256 hash of the device token.', max_length=64, unique=True),
        ),
    ]
