# Generated by Django 6.0.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_devicetoken_last_seen_alter_devicetoken_key"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_public_key",
                    models.TextField(help_text="Base64-encoded Ed25519 public key"),
                ),
                (
                    "next_public_key",
                    models.TextField(
                        blank=True,
                        help_text="Pending key for A/B rotation",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "station",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_key",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "device key",
                "verbose_name_plural": "device keys",
            },
        ),
    ]
