# Generated by Django 6.0.5 on 2026-05-19 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='granted at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='application')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_app_grants', to=settings.AUTH_USER_MODEL, verbose_name='granted by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_grants', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'app grant',
                'verbose_name_plural': 'app grants',
                'indexes': [models.Index(fields=['application', 'revoked_at'], name='sso_appgran_applica_4eea08_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'application'), name='uniq_active_grant_per_user_per_app')],
            },
        ),
    ]
