# Generated by Django 6.0.5 on 2026-05-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appgrant',
            options={'ordering': ('-granted_at',), 'verbose_name': 'app grant', 'verbose_name_plural': 'app grants'},
        ),
    ]
