# Generated by Django 6.0.5 on 2026-05-19 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_alter_appgrant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SsoAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('app_registered', 'App Registered'), ('app_deleted', 'App Deleted'), ('grant_given', 'Grant Given'), ('grant_revoked', 'Grant Revoked'), ('login_success', 'Login Success'), ('login_denied_no_grant', 'Login Denied — No Grant'), ('login_denied_inactive', 'Login Denied — Inactive User'), ('token_revoked', 'Token Revoked')], max_length=32, verbose_name='event type')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso_audit_logs_as_actor', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='application')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso_audit_logs_as_target', to=settings.AUTH_USER_MODEL, verbose_name='target user')),
            ],
            options={
                'verbose_name': 'SSO audit log',
                'verbose_name_plural': 'SSO audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sso_ssoaudi_created_012b5a_idx'), models.Index(fields=['event_type', '-created_at'], name='sso_ssoaudi_event_t_ee1fad_idx'), models.Index(fields=['target_user', '-created_at'], name='sso_ssoaudi_target__f393f3_idx')],
            },
        ),
    ]
