# Generated by Django 6.0.6 on 2026-06-08 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0003_ssoauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_policy', models.CharField(choices=[('grant_required', 'Grant required (default)'), ('open_to_all', 'Open to all (incl. applicants)'), ('open_to_members', 'Open to members and above'), ('open_to_internal', 'Open to staff and admins'), ('open_to_admins', 'Open to admins only')], default='grant_required', max_length=32, verbose_name='access policy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_policy', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='application')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_app_policies', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name': 'application policy',
                'verbose_name_plural': 'application policies',
            },
        ),
    ]
