# Generated by Django 6.0.6 on 2026-06-08 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_application_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='country code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='issued at')),
                ('last_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='last seen at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('revoke_reason', models.CharField(blank=True, choices=[('admin_revoke', 'Admin revoke'), ('user_logout', 'User logout'), ('user_deactivated', 'User deactivated'), ('grant_revoked', 'Grant revoked'), ('rotated', 'Rotated (refresh)')], max_length=32, verbose_name='revoke reason')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_sessions', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='application')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sso.tokensession', verbose_name='parent session')),
                ('refresh_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sso_session', to=settings.OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL, verbose_name='refresh token')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_sessions', to=settings.AUTH_USER_MODEL, verbose_name='revoked by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'token session',
                'verbose_name_plural': 'token sessions',
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['user', '-issued_at'], name='sso_tokense_user_id_5319b2_idx'), models.Index(fields=['application', '-issued_at'], name='sso_tokense_applica_627708_idx'), models.Index(fields=['revoked_at'], name='sso_tokense_revoked_0d9b85_idx')],
            },
        ),
    ]
