# Generated by Django 6.0.6 on 2026-06-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0005_token_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoauditlog',
            name='event_type',
            field=models.CharField(choices=[('app_registered', 'App Registered'), ('app_deleted', 'App Deleted'), ('grant_given', 'Grant Given'), ('grant_revoked', 'Grant Revoked'), ('login_success', 'Login Success'), ('login_denied_no_grant', 'Login Denied — No Grant'), ('login_denied_inactive', 'Login Denied — Inactive User'), ('token_revoked', 'Token Revoked'), ('session_revoked', 'Session Revoked (admin)'), ('app_policy_changed', 'App Policy Changed'), ('group_membership_changed', 'Group Membership Changed')], max_length=32, verbose_name='event type'),
        ),
    ]
