# Generated by Django 6.0.3 on 2026-07-18 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0014_remove_moduletype_installed_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=64, verbose_name='slot')),
                ('module_id', models.CharField(max_length=128, verbose_name='module id')),
                ('type', models.CharField(blank=True, max_length=128, verbose_name='type')),
                ('model', models.CharField(blank=True, max_length=128, verbose_name='model')),
                ('version', models.CharField(blank=True, max_length=64, verbose_name='version')),
                ('capability_descriptor', models.JSONField(blank=True, default=list, verbose_name='capability descriptor')),
                ('last_state', models.JSONField(blank=True, default=dict, verbose_name='last state')),
                ('online', models.BooleanField(default=False, verbose_name='online')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='last seen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='stations.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'station module',
                'verbose_name_plural': 'station modules',
                'ordering': ['station', 'slot', 'module_id'],
                'indexes': [models.Index(fields=['station', 'online'], name='control_sta_station_178225_idx')],
                'constraints': [models.UniqueConstraint(fields=('station', 'slot', 'module_id'), name='uniq_station_slot_module')],
            },
        ),
    ]
