# Generated by Django 6.0.3 on 2026-07-18 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
        ('stations', '0014_remove_moduletype_installed_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='station', max_length=64, verbose_name='scope')),
                ('acquired_at', models.DateTimeField(blank=True, null=True, verbose_name='acquired at')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='last activity')),
                ('pending_release_at', models.DateTimeField(blank=True, null=True, verbose_name='pending release at')),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_control_locks', to=settings.AUTH_USER_MODEL, verbose_name='holder')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_locks', to='stations.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'control lock',
                'verbose_name_plural': 'control locks',
                'constraints': [models.UniqueConstraint(fields=('station', 'scope'), name='uniq_station_scope_lock')],
            },
        ),
    ]
