# Generated by Django 6.0.3 on 2026-09-13 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_controllock'),
        ('module_firmware', '0003_moduleassignmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmodule',
            name='tracked_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_modules', to='module_firmware.module', verbose_name='module'),
        ),
    ]
