# Generated by Django 6.0.3 on 2026-10-04 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_stationmodule_tracked_module'),
        ('stations', '0025_station_tx_audio_ceiling_dbfs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistedCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=64, verbose_name='slot')),
                ('module_id', models.CharField(max_length=128, verbose_name='module id')),
                ('capability', models.CharField(max_length=64, verbose_name='capability')),
                ('value', models.JSONField(verbose_name='value')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persisted_capabilities', to='stations.station', verbose_name='station')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'persisted capability',
                'verbose_name_plural': 'persisted capabilities',
                'ordering': ['station', 'slot', 'module_id', 'capability'],
                'constraints': [models.UniqueConstraint(fields=('station', 'slot', 'module_id', 'capability'), name='uniq_persisted_cap')],
            },
        ),
    ]
