# Generated by Django 6.1.1 on 2026-10-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_persistedcapability'),
        ('stations', '0025_station_tx_audio_ceiling_dbfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('control', 'control'), ('audio', 'audio'), ('terminal', 'terminal')], max_length=16, verbose_name='kind')),
                ('channel_name', models.CharField(max_length=255, verbose_name='channel name')),
                ('connected_at', models.DateTimeField(auto_now=True, verbose_name='connected at')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_connections', to='stations.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'agent connection',
                'verbose_name_plural': 'agent connections',
                'constraints': [models.UniqueConstraint(fields=('station', 'kind'), name='uniq_agent_connection')],
            },
        ),
    ]
