# Generated by Django 6.0.4 on 2026-04-12 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_devicetoken_last_seen_alter_devicetoken_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('firmware_flash_method', models.CharField(choices=[('usb_dfu', 'USB DFU'), ('uart', 'UART'), ('spi', 'SPI'), ('other', 'Other')], default='other', max_length=10, verbose_name='firmware flash method')),
            ],
            options={
                'verbose_name': 'module type',
                'verbose_name_plural': 'module types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'station group',
                'verbose_name_plural': 'station groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('callsign', models.CharField(blank=True, max_length=20, verbose_name='callsign')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='location name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('altitude', models.IntegerField(blank=True, help_text='Meters above sea level', null=True, verbose_name='altitude')),
                ('hardware_revision', models.CharField(blank=True, max_length=50, verbose_name='hardware revision')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('current_os_version', models.CharField(blank=True, max_length=100, verbose_name='current OS version')),
                ('current_agent_version', models.CharField(blank=True, max_length=50, verbose_name='current agent version')),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='last IP address')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='last seen')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('updating', 'Updating'), ('error', 'Error')], default='offline', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('device_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station', to='api.devicetoken', verbose_name='device token')),
                ('installed_modules', models.ManyToManyField(blank=True, related_name='stations', to='stations.moduletype', verbose_name='installed modules')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='stations.stationgroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'station',
                'verbose_name_plural': 'stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StationLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('note', 'Note'), ('maintenance', 'Maintenance'), ('incident', 'Incident'), ('update', 'Update'), ('deployment', 'Deployment')], default='note', max_length=12, verbose_name='entry type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='stations.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'station log entry',
                'verbose_name_plural': 'station log entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stations/photos/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stations.station', verbose_name='station')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_photos', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'station photo',
                'verbose_name_plural': 'station photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
