# Generated by Django 6.0.4 on 2026-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#6c757d', help_text='Hex color for the tag badge, e.g. #0d6efd', max_length=7, verbose_name='color')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'station tag',
                'verbose_name_plural': 'station tags',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='station',
            name='group',
        ),
        migrations.AddField(
            model_name='station',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='stations', to='stations.stationtag', verbose_name='tags'),
        ),
        migrations.DeleteModel(
            name='StationGroup',
        ),
    ]
