# Generated by Django 6.0.4 on 2026-04-12 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_stationtag_remove_station_group_station_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_change', 'Status Change'), ('heartbeat', 'Heartbeat'), ('token_generated', 'Token Generated'), ('token_revoked', 'Token Revoked'), ('firmware_update', 'Firmware Update')], max_length=20, verbose_name='event type')),
                ('message', models.TextField(verbose_name='message')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON dict of changed fields: {field: {old, new}}', verbose_name='changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='stations.station', verbose_name='station')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'station audit log',
                'verbose_name_plural': 'station audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='stations_st_created_241fc5_idx'), models.Index(fields=['station', '-created_at'], name='stations_st_station_a9c418_idx')],
            },
        ),
    ]
