# Generated by Django 6.0.4 on 2026-04-13 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_stationauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Hardware inventory data from agent', verbose_name='data')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='stations.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'station inventory',
                'verbose_name_plural': 'station inventories',
            },
        ),
    ]
