# Generated by Django 6.0.4 on 2026-04-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_device_key'),
        ('stations', '0004_stationinventory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['status', 'last_seen'], name='stations_st_status_bed7d9_idx'),
        ),
    ]
