# Generated by Django 6.0.4 on 2026-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_remove_station_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationauditlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_change', 'Status Change'), ('heartbeat', 'Heartbeat'), ('token_generated', 'Token Generated'), ('token_revoked', 'Token Revoked'), ('firmware_update', 'Firmware Update'), ('provisioning_requested', 'Provisioning Requested'), ('provisioning_ready', 'Provisioning Ready'), ('provisioning_downloaded', 'Provisioning Downloaded'), ('provisioning_failed', 'Provisioning Failed'), ('provisioning_expired', 'Provisioning Expired')], max_length=32, verbose_name='event type'),
        ),
    ]
