# Generated by Django 6.0.4 on 2026-04-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_imageimportjob_options_and_more'),
        ('stations', '0007_provisioning_audit_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='current_image_release',
            field=models.ForeignKey(blank=True, help_text='The image release last used to provision this station. Set when a provisioning bundle is downloaded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations_provisioned_with', to='images.imagerelease', verbose_name='provisioned with image'),
        ),
    ]
