# Generated by Django 6.0.4 on 2026-04-19 15:03
#
# Hand-edited to rename any pre-existing StationTag rows that happen to
# carry a now-reserved slug before the CheckConstraint lands — otherwise
# the AddConstraint would fail at migrate time on an upgrade to any DB
# that has such a row.

from django.db import migrations, models


RESERVED_SLUGS = ["__unassigned__"]


def rename_conflicting_tags(apps, schema_editor):
    """Rename tags carrying a reserved slug out of the way.

    Picks "<slug>-legacy-<pk>" as the new slug (guaranteed unique since
    pk is). The name is left untouched so a human can still spot it.
    """
    StationTag = apps.get_model("stations", "StationTag")
    for tag in StationTag.objects.filter(slug__in=RESERVED_SLUGS):
        tag.slug = f"{tag.slug}-legacy-{tag.pk}"
        tag.save(update_fields=["slug"])


def noop_reverse(apps, schema_editor):
    # No reverse: we can't know which legacy-* slugs were renamed by
    # this migration vs. manually set. Leaving them alone on rollback is
    # safe — the reservation will just no longer be enforced.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0008_station_current_image_release"),
    ]

    operations = [
        migrations.RunPython(rename_conflicting_tags, noop_reverse),
        migrations.AddConstraint(
            model_name="stationtag",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug__in", RESERVED_SLUGS), _negated=True),
                name="stationtag_slug_not_reserved",
            ),
        ),
    ]
