# Generated by Django 6.0.4 on 2026-04-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_station_current_image_release'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stationtag',
            constraint=models.CheckConstraint(condition=models.Q(('slug__in', ['__unassigned__']), _negated=True), name='stationtag_slug_not_reserved'),
        ),
    ]
