# Generated by Django 6.0.6 on 2026-06-05 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0010_add_region_and_station_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("manager", "Region-Manager")], max_length=10, verbose_name="role"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="assigned at"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_region_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned by",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="stations.region",
                        verbose_name="region",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "region assignment",
                "verbose_name_plural": "region assignments",
                "ordering": ["region", "user"],
                "indexes": [
                    models.Index(fields=["region", "role"], name="stations_re_region__bee8a8_idx"),
                    models.Index(fields=["user"], name="stations_re_user_id_877e0f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "region", "role"), name="uniq_user_role_per_region"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Station-Admin"), ("maintainer", "Station-Maintainer")],
                        max_length=12,
                        verbose_name="role",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="assigned at"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_station_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned by",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="stations.station",
                        verbose_name="station",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "station assignment",
                "verbose_name_plural": "station assignments",
                "ordering": ["station", "role", "user"],
                "indexes": [
                    models.Index(
                        fields=["station", "role"], name="stations_st_station_882d84_idx"
                    ),
                    models.Index(fields=["user"], name="stations_st_user_id_58b173_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "station"), name="uniq_user_per_station_assignment"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "admin")),
                        fields=("station",),
                        name="uniq_admin_per_station",
                    ),
                ],
            },
        ),
    ]
