# Generated by Django 6.0.6 on 2026-06-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_extend_station_audit_event_types'),
    ]

    operations = [
        # Die firmware/builder-Tabellen sind in Prod verifiziert leer (2026-06-21)
        # und die Apps sind entfernt. Wir droppen die orphaned Tabellen + die
        # zugehörigen django_migrations-Zeilen idempotent. firmware vor stations_
        # moduletype-Drop (Task 0014), weil firmware_firmwareartifact.target_module
        # einen FK auf stations_moduletype hält. Auf frischer DB (Test/CI) sind die
        # Tabellen nie entstanden → IF EXISTS macht no-op.
        migrations.RunSQL(
            sql="""
            DROP TABLE IF EXISTS builder_buildjob CASCADE;
            DROP TABLE IF EXISTS builder_buildconfig CASCADE;
            DROP TABLE IF EXISTS firmware_firmwaredelta CASCADE;
            DROP TABLE IF EXISTS firmware_firmwareartifact CASCADE;
            DELETE FROM django_migrations WHERE app IN ('firmware', 'builder');
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
