# Generated by Django 6.0.6 on 2026-06-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_drop_legacy_firmware_builder_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='installed_modules',
        ),
        migrations.DeleteModel(
            name='ModuleType',
        ),
    ]
