# Generated by Django 6.0.3 on 2026-07-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_remove_moduletype_installed_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationauditlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_change', 'Status Change'), ('heartbeat', 'Heartbeat'), ('token_generated', 'Token Generated'), ('token_revoked', 'Token Revoked'), ('firmware_update', 'Firmware Update'), ('provisioning_requested', 'Provisioning Requested'), ('provisioning_ready', 'Provisioning Ready'), ('provisioning_downloaded', 'Provisioning Downloaded'), ('provisioning_failed', 'Provisioning Failed'), ('provisioning_expired', 'Provisioning Expired'), ('station_assignment_created', 'Station Assignment Created'), ('station_assignment_revoked', 'Station Assignment Revoked'), ('station_region_changed', 'Station Region Changed'), ('control_lock_acquired', 'Control Lock Acquired'), ('control_lock_released', 'Control Lock Released'), ('control_lock_transferred', 'Control Lock Transferred'), ('control_lock_preempted', 'Control Lock Preempted'), ('control_command', 'Control Command'), ('control_ptt', 'Control PTT')], max_length=32, verbose_name='event type'),
        ),
    ]
