# Generated by Django 6.0.3 on 2026-09-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_alter_stationauditlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='current_image_variant',
            field=models.CharField(blank=True, default='', help_text='Baked image channel (VARIANT_ID) reported by the agent heartbeat.', max_length=32, verbose_name='current image variant'),
        ),
    ]
