# Generated by Django 6.0.7 on 2026-09-10 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0017_station_audio_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='audio_enabled',
        ),
    ]
