# Generated by Django 6.0.3 on 2026-09-13 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_firmware', '0003_moduleassignmenthistory'),
        ('stations', '0018_remove_station_audio_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stationauditlog',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='module_firmware.module', verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='stationauditlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_change', 'Status Change'), ('heartbeat', 'Heartbeat'), ('token_generated', 'Token Generated'), ('token_revoked', 'Token Revoked'), ('firmware_update', 'Firmware Update'), ('provisioning_requested', 'Provisioning Requested'), ('provisioning_ready', 'Provisioning Ready'), ('provisioning_downloaded', 'Provisioning Downloaded'), ('provisioning_failed', 'Provisioning Failed'), ('provisioning_expired', 'Provisioning Expired'), ('station_assignment_created', 'Station Assignment Created'), ('station_assignment_revoked', 'Station Assignment Revoked'), ('station_region_changed', 'Station Region Changed'), ('control_lock_acquired', 'Control Lock Acquired'), ('control_lock_released', 'Control Lock Released'), ('control_lock_transferred', 'Control Lock Transferred'), ('control_lock_preempted', 'Control Lock Preempted'), ('control_command', 'Control Command'), ('control_ptt', 'Control PTT'), ('module_discovered', 'Module Discovered'), ('module_registered', 'Module Registered'), ('module_swapped', 'Module Swapped'), ('module_lifecycle_changed', 'Module Lifecycle Changed'), ('module_assignment_changed', 'Module Assignment Changed')], max_length=32, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='stationauditlog',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='stations.station', verbose_name='station'),
        ),
        migrations.AddIndex(
            model_name='stationauditlog',
            index=models.Index(fields=['module', '-created_at'], name='stations_st_module__759310_idx'),
        ),
    ]
