# Generated by Django 6.0.3 on 2026-09-14 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0019_stationauditlog_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationauditlog',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='stations.station', verbose_name='station'),
        ),
    ]
