# Generated by Django 6.0.3 on 2026-09-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0020_alter_stationauditlog_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationauditlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_change', 'Status Change'), ('heartbeat', 'Heartbeat'), ('token_generated', 'Token Generated'), ('token_revoked', 'Token Revoked'), ('firmware_update', 'Firmware Update'), ('provisioning_requested', 'Provisioning Requested'), ('provisioning_ready', 'Provisioning Ready'), ('provisioning_downloaded', 'Provisioning Downloaded'), ('provisioning_failed', 'Provisioning Failed'), ('provisioning_expired', 'Provisioning Expired'), ('station_assignment_created', 'Station Assignment Created'), ('station_assignment_revoked', 'Station Assignment Revoked'), ('station_region_changed', 'Station Region Changed'), ('control_lock_acquired', 'Control Lock Acquired'), ('control_lock_released', 'Control Lock Released'), ('control_lock_transferred', 'Control Lock Transferred'), ('control_lock_preempted', 'Control Lock Preempted'), ('control_command', 'Control Command'), ('control_ptt', 'Control PTT'), ('module_discovered', 'Module Discovered'), ('module_registered', 'Module Registered'), ('module_swapped', 'Module Swapped'), ('module_lifecycle_changed', 'Module Lifecycle Changed'), ('module_assignment_changed', 'Module Assignment Changed'), ('firmware_target_set', 'Firmware Target Set'), ('module_flash_started', 'Module Flash Started'), ('module_flash_success', 'Module Flash Success'), ('module_flash_rolled_back', 'Module Flash Rolled Back'), ('module_flash_rejected', 'Module Flash Rejected'), ('module_flash_failed', 'Module Flash Failed'), ('module_quarantined', 'Module Quarantined')], max_length=32, verbose_name='event type'),
        ),
    ]
