# Generated by Django 6.0.3 on 2026-10-01 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0021_c_firmware_audit_event_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationauditlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_change', 'Status Change'), ('heartbeat', 'Heartbeat'), ('token_generated', 'Token Generated'), ('token_revoked', 'Token Revoked'), ('firmware_update', 'Firmware Update'), ('provisioning_requested', 'Provisioning Requested'), ('provisioning_ready', 'Provisioning Ready'), ('provisioning_downloaded', 'Provisioning Downloaded'), ('provisioning_failed', 'Provisioning Failed'), ('provisioning_expired', 'Provisioning Expired'), ('station_assignment_created', 'Station Assignment Created'), ('station_assignment_revoked', 'Station Assignment Revoked'), ('station_region_changed', 'Station Region Changed'), ('control_lock_acquired', 'Control Lock Acquired'), ('control_lock_released', 'Control Lock Released'), ('control_lock_transferred', 'Control Lock Transferred'), ('control_lock_preempted', 'Control Lock Preempted'), ('control_command', 'Control Command'), ('control_ptt', 'Control PTT'), ('module_discovered', 'Module Discovered'), ('module_registered', 'Module Registered'), ('module_swapped', 'Module Swapped'), ('module_lifecycle_changed', 'Module Lifecycle Changed'), ('module_assignment_changed', 'Module Assignment Changed'), ('firmware_target_set', 'Firmware Target Set'), ('module_flash_started', 'Module Flash Started'), ('module_flash_success', 'Module Flash Success'), ('module_flash_rolled_back', 'Module Flash Rolled Back'), ('module_flash_rejected', 'Module Flash Rejected'), ('module_flash_failed', 'Module Flash Failed'), ('module_quarantined', 'Module Quarantined'), ('reboot', 'Reboot')], max_length=32, verbose_name='event type'),
        ),
        migrations.CreateModel(
            name='StationTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('boot_id', models.CharField(blank=True, max_length=64)),
                ('boot_count', models.PositiveIntegerField(default=0)),
                ('last_reboot_reason', models.CharField(blank=True, max_length=16)),
                ('last_reboot_at', models.DateTimeField(blank=True, null=True)),
                ('uptime_seconds', models.FloatField(blank=True, null=True)),
                ('undervoltage_now', models.BooleanField(null=True)),
                ('undervoltage_occurred', models.BooleanField(null=True)),
                ('throttled_now', models.BooleanField(null=True)),
                ('throttled_occurred', models.BooleanField(null=True)),
                ('active_slot', models.CharField(blank=True, max_length=1)),
                ('image_version', models.CharField(blank=True, max_length=100)),
                ('last_ota_result', models.CharField(blank=True, max_length=16)),
                ('worst_life_time_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('worst_pre_eol', models.CharField(blank=True, max_length=8)),
                ('io_error_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='stations.station')),
            ],
        ),
    ]
