# Generated by Django 6.0.3 on 2026-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0022_alter_stationauditlog_event_type_stationtelemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationtelemetry',
            name='alerted_io_error_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
