# Generated by Django 6.0.3 on 2026-10-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0023_stationtelemetry_alerted_io_error_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationtelemetry",
            name="power_alerted_boot_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
