# Generated by Django 6.0.3 on 2026-10-04 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0024_stationtelemetry_power_alerted_boot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='tx_audio_ceiling_dbfs',
            field=models.FloatField(blank=True, help_text='Per-board calibration: agent limiter ceiling that yields the target FM deviation. Empty = conservative default (-12 dBFS).', null=True, validators=[django.core.validators.MinValueValidator(-24.0), django.core.validators.MaxValueValidator(-3.0)], verbose_name='TX audio ceiling (dBFS)'),
        ),
    ]
