# Generated by Django 6.0.4 on 2026-04-13 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firmware', '0002_initial'),
        ('stations', '0003_stationauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('custom_config', models.JSONField(blank=True, default=dict, verbose_name='custom config')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='build_configs_as_base', to='firmware.firmwareartifact', verbose_name='base image')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_configs', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('extra_firmware', models.ManyToManyField(blank=True, related_name='build_configs_as_extra', to='firmware.firmwareartifact', verbose_name='extra firmware')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_configs', to='stations.station', verbose_name='station')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_configs', to='stations.stationtag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'build config',
                'verbose_name_plural': 'build configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='status')),
                ('log', models.TextField(blank=True, verbose_name='log')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('build_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='builder.buildconfig', verbose_name='build config')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_jobs', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('output_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_jobs', to='firmware.firmwareartifact', verbose_name='output artifact')),
            ],
            options={
                'verbose_name': 'build job',
                'verbose_name_plural': 'build jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
