# Generated by Django 6.0.4 on 2026-04-13 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firmware', '0002_initial'),
        ('stations', '0003_stationauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('tag', 'By Tag'), ('station', 'Single Station'), ('all', 'All Stations')], max_length=10, verbose_name='target type')),
                ('strategy', models.CharField(choices=[('immediate', 'Immediate'), ('phased', 'Phased')], default='immediate', max_length=10, verbose_name='strategy')),
                ('phase_config', models.JSONField(blank=True, default=dict, help_text='e.g. {"batch_size": 2, "delay_seconds": 3600}', verbose_name='phase configuration')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('firmware_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='firmware.firmwareartifact', verbose_name='firmware artifact')),
                ('target_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_deployments', to='stations.station', verbose_name='target station')),
                ('target_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='stations.stationtag', verbose_name='target tag')),
            ],
            options={
                'verbose_name': 'deployment',
                'verbose_name_plural': 'deployments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('installing', 'Installing'), ('rebooting', 'Rebooting'), ('verifying', 'Verifying'), ('success', 'Success'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('cancelled', 'Cancelled')], default='pending', max_length=16, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('previous_version', models.CharField(blank=True, max_length=100, verbose_name='previous version')),
                ('new_version', models.CharField(blank=True, max_length=100, verbose_name='new version')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='deployments.deployment', verbose_name='deployment')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployment_results', to='stations.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'deployment result',
                'verbose_name_plural': 'deployment results',
                'ordering': ['-pk'],
                'indexes': [models.Index(fields=['deployment', 'status'], name='deployments_deploym_59966e_idx'), models.Index(fields=['station', 'status'], name='deployments_station_6b468b_idx')],
                'unique_together': {('deployment', 'station')},
            },
        ),
    ]
