# Generated by Django 6.0.7 on 2026-09-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0016_station_current_image_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptt_active', models.BooleanField(default=False, verbose_name='PTT active')),
                ('ptt_slot', models.IntegerField(blank=True, null=True, verbose_name='PTT slot')),
                ('ptt_module', models.CharField(blank=True, max_length=128, verbose_name='PTT module')),
                ('ptt_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='PTT expires at')),
                ('tx_slot', models.IntegerField(blank=True, null=True, verbose_name='TX slot')),
                ('tx_module', models.CharField(blank=True, max_length=128, verbose_name='TX module')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_gate', to='stations.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'audio gate',
                'verbose_name_plural': 'audio gates',
            },
        ),
        migrations.CreateModel(
            name='AudioSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=128, verbose_name='stream id')),
                ('channel_name', models.CharField(max_length=255, verbose_name='channel name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_subscriptions', to='stations.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'audio subscription',
                'verbose_name_plural': 'audio subscriptions',
                'indexes': [models.Index(fields=['station', 'stream_id'], name='audio_audio_station_bf1997_idx'), models.Index(fields=['station', 'channel_name'], name='audio_audio_station_b5c1fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('station', 'stream_id', 'channel_name'), name='uniq_audio_sub_station_stream_channel')],
            },
        ),
    ]
