# Generated by Django 6.0.4 on 2026-04-13 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0004_stationinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('station_offline', 'Station Offline'), ('cpu_temperature', 'CPU Temperature'), ('disk_warning', 'Disk Warning'), ('disk_critical', 'Disk Critical'), ('ram_critical', 'RAM Critical'), ('ota_failed', 'OTA Failed')], max_length=20, unique=True, verbose_name='alert type')),
                ('threshold', models.FloatField(help_text='e.g. 80.0 for CPU temp, 90.0 for disk %, 90.0 for RAM %', verbose_name='threshold')),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=10, verbose_name='severity')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'alert rule',
                'verbose_name_plural': 'alert rules',
                'ordering': ['alert_type'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=10, verbose_name='severity')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='acknowledged')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='acknowledged by')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stations.station', verbose_name='station')),
                ('alert_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.alertrule', verbose_name='alert rule')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved', 'severity', 'created_at'], name='monitoring__is_reso_90527b_idx')],
            },
        ),
    ]
