# Generated by Django 6.0.3 on 2026-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_seed_default_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='alert_type',
            field=models.CharField(choices=[('station_offline', 'Station Offline'), ('cpu_temperature', 'CPU Temperature'), ('disk_warning', 'Disk Warning'), ('disk_critical', 'Disk Critical'), ('ram_critical', 'RAM Critical'), ('ota_failed', 'OTA Failed'), ('unexpected_reboot', 'Unexpected Reboot'), ('power_warning', 'Power Warning'), ('storage_health', 'Storage Health')], max_length=20, unique=True, verbose_name='alert type'),
        ),
    ]
