# Generated by Django 6.0.4 on 2026-04-17 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0004_alter_imageimportjob_options_and_more'),
        ('stations', '0006_remove_station_device_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('downloaded', 'Downloaded'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=16, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('output_s3_key', models.CharField(blank=True, max_length=512, verbose_name='output S3 key')),
                ('output_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='output size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='ready at')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='downloaded at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('image_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_jobs', to='images.imagerelease', verbose_name='image release')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_jobs', to='stations.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'provisioning job',
                'verbose_name_plural': 'provisioning jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
