# Generated by Django 6.0.4 on 2026-04-19 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0008_station_current_image_release'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolloutSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rollout_sequences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rollout sequence',
                'verbose_name_plural': 'rollout sequences',
            },
        ),
        migrations.CreateModel(
            name='RolloutSequenceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='position')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rollouts.rolloutsequence')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollout_entries', to='stations.stationtag')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('sequence', 'tag'), name='uniq_tag_per_sequence'), models.UniqueConstraint(fields=('sequence', 'position'), name='uniq_position_per_sequence')],
            },
        ),
    ]
