# Generated by Django 6.0.4 on 2026-04-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rollouts", "0002_seed_singleton"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolloutsequence",
            name="singleton_key",
            field=models.CharField(
                default="current",
                editable=False,
                help_text="Fixed value; the unique index makes this table a singleton.",
                max_length=16,
                unique=True,
            ),
        ),
    ]
