# Generated by Django 6.0.4 on 2026-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('version', models.CharField(max_length=50, verbose_name='version')),
                ('artifact_type', models.CharField(choices=[('os_image', 'OS Image'), ('module_firmware', 'Module Firmware')], default='os_image', max_length=20, verbose_name='artifact type')),
                ('file', models.FileField(upload_to='firmware/artifacts/%Y/%m/', verbose_name='file')),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='file size')),
                ('checksum_sha256', models.CharField(default='', editable=False, max_length=64, verbose_name='SHA-256 checksum')),
                ('release_notes', models.TextField(blank=True, verbose_name='release notes')),
                ('is_stable', models.BooleanField(default=False, verbose_name='stable release')),
                ('compatible_hw_revisions', models.CharField(blank=True, help_text='Comma-separated list of compatible hardware revisions.', max_length=500, verbose_name='compatible hardware revisions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'firmware artifact',
                'verbose_name_plural': 'firmware artifacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
