# Generated by Django 6.0.4 on 2026-04-12 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firmware', '0001_initial'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwareartifact',
            name='target_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmware_artifacts', to='stations.moduletype', verbose_name='target module'),
        ),
        migrations.AddField(
            model_name='firmwareartifact',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_firmware', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.AlterUniqueTogether(
            name='firmwareartifact',
            unique_together={('name', 'version')},
        ),
    ]
