# Generated by Django 6.0.4 on 2026-04-13 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_file', models.FileField(upload_to='firmware/deltas/%Y/%m/', verbose_name='delta file')),
                ('delta_size', models.PositiveBigIntegerField(editable=False, verbose_name='delta size')),
                ('checksum_sha256', models.CharField(editable=False, max_length=64, verbose_name='SHA-256 checksum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('source_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas_as_source', to='firmware.firmwareartifact', verbose_name='source artifact')),
                ('target_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas_as_target', to='firmware.firmwareartifact', verbose_name='target artifact')),
            ],
            options={
                'verbose_name': 'firmware delta',
                'verbose_name_plural': 'firmware deltas',
                'unique_together': {('source_artifact', 'target_artifact')},
            },
        ),
    ]
